#!/usr/bin/env bash
# Redeploy code to the install prefix after editing it. For development —
# scripts/install.sh does this (and everything else) on a fresh machine.
#
# Reads the paths chosen at install time from /etc/kb/kb.env, so it follows a
# non-default --prefix automatically. Run as root:
#
#   sudo bash scripts/deploy.sh [--no-restart]
#
# WARNING: restarting kb-hub kills every open web-terminal session. The units use
# systemd's default KillMode=control-group, and the per-user backends (plus their
# login shells) are spawned by the hub and therefore live in its cgroup. Check for
# live work first — `systemctl status kb-hub | sed -n '/CGroup/,$p'` — and pass
# --no-restart if someone is mid-session. kb-syncd, kb-indexer, kb-embedd and
# kb-convert contain only themselves, so those restarts are safe; a kb-syncd restart can
# however lose CRDT edits that have not yet been flushed to disk.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESTART=1
[ "${1:-}" = "--no-restart" ] && RESTART=0

[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

# Defaults match install.sh; /etc/kb/kb.env overrides them if it exists.
PREFIX=/opt/kb-platform
VENV=/opt/kb-venv
if [ -f /etc/kb/kb.env ]; then
  # shellcheck disable=SC1091
  . /etc/kb/kb.env
  PREFIX="${KB_PLATFORM_ROOT:-$PREFIX}"
  VENV="$(dirname "$(dirname "${KB_VENV_PY:-$VENV/bin/python}")")"
else
  echo "WARNING: /etc/kb/kb.env not found — is the platform installed? Using defaults."
fi

echo "== code -> $PREFIX =="
mkdir -p "$PREFIX/frontend"
rsync -a --delete "$SRC/kb_platform" "$PREFIX/"
rsync -a --delete "$SRC/scripts"     "$PREFIX/"
if [ -d "$SRC/frontend/static" ] && [ -n "$(ls -A "$SRC/frontend/static" 2>/dev/null)" ]; then
  rsync -a --delete "$SRC/frontend/static" "$PREFIX/frontend/"
else
  echo "  (no frontend/static — run 'cd frontend && npm install && node build.mjs' first)"
fi
cp "$SRC/requirements.txt" "$PREFIX/" 2>/dev/null || true

echo "== permissions (world-readable code; NOT the session key) =="
chown -R root:root "$PREFIX"
chmod -R a+rX "$PREFIX"

# The kb-history wrapper is generated by install.sh, which nobody re-runs after
# the first install — so a fix to it never reached an existing box. That is not
# hypothetical: this wrapper sat here for weeks without the PYTHONPATH every
# systemd unit sets, and `kb-history` answered ModuleNotFoundError every time
# anyone tried the documented way to read version history. Regenerating it on
# every deploy is idempotent and costs nothing.
echo "== kb-history and kb-search CLIs =="
cat > /usr/local/bin/kb-history <<WRAP
#!/bin/sh
# Ollsoft Company OS version-history CLI. Regenerated by scripts/deploy.sh.
PYTHONPATH="$PREFIX" exec "$VENV/bin/python" -m kb_platform.vc_cli "\$@"
WRAP
chmod 0755 /usr/local/bin/kb-history
# kb-search: hybrid search as the caller (docs/semantic-search.md).
cat > /usr/local/bin/kb-search <<WRAP
#!/bin/sh
# Ollsoft Company OS search CLI. Regenerated by scripts/deploy.sh.
PYTHONPATH="$PREFIX" exec "$VENV/bin/python" -m kb_platform.search_cli "\$@"
WRAP
chmod 0755 /usr/local/bin/kb-search

# The platform's skills (company-skills/) are platform code: install them on
# every deploy, like the CLI wrappers, or a fix never reaches an existing box.
# Only the platform's own — a skill the company wrote itself is left alone.
REPO_DIR="${KB_REPO:-/srv/kb}"
if [ -d "$REPO_DIR/.claude/skills" ]; then
  echo "== skills -> $REPO_DIR/.claude/skills =="
  for d in "$SRC"/company-skills/*/; do
    name="$(basename "$d")"
    install -d -m 0755 -o root -g kb-users "$REPO_DIR/.claude/skills/$name"
    install -m 0644 -o root -g kb-users "$d/SKILL.md" "$REPO_DIR/.claude/skills/$name/SKILL.md"
  done
fi

# schema.sql is idempotent (CREATE ... IF NOT EXISTS, CREATE OR REPLACE), so a
# deploy brings an existing database up to the code it ships — new tables such
# as kb.chunks and kb.embeddings included. One transaction: all or nothing.
# It re-creates the RLS policies on kb.blocks, which needs a moment's exclusive
# lock: lock_timeout keeps searches from queueing behind it while the indexer
# is mid-transaction, and the retry takes the next gap.
echo "== database schema =="
DB="${KB_PG_DB:-kb}"
runuser -u postgres -- psql -d "$DB" -qc "CREATE EXTENSION IF NOT EXISTS vector;" >/dev/null
runuser -u postgres -- psql -d "$DB" -qc "ALTER EXTENSION vector UPDATE;" >/dev/null 2>&1 || true
applied=0
for try in 1 2 3 4 5; do
  if PGOPTIONS="-c lock_timeout=3s" runuser -u kbindexer -- \
       psql -d "$DB" -q -1 -v ON_ERROR_STOP=1 < "$SRC/scripts/schema.sql" >/dev/null 2>"/tmp/kb-schema.$$"; then
    applied=1; break
  fi
  grep -q "lock timeout" "/tmp/kb-schema.$$" || break
  sleep "$try"
done
if [ "$applied" -eq 1 ]; then
  echo "  schema up to date"; rm -f "/tmp/kb-schema.$$"
else
  echo "!! schema.sql did not apply (nothing was changed):" >&2
  cat "/tmp/kb-schema.$$" >&2; rm -f "/tmp/kb-schema.$$"; exit 1
fi

echo "== systemd units =="
CVENV="${VENV%/*}/kb-convert-venv"
cp "$SRC/systemd/kb.conf" /etc/tmpfiles.d/kb.conf
cp "$SRC/systemd/kb-logrotate.conf" /etc/logrotate.d/kb
install -d -m 750 -o root -g root /var/log/kb
for u in "$SRC"/systemd/kb-*.service "$SRC"/systemd/kb-*.timer; do
  [ -e "$u" ] || continue
  # convert-venv first: longest path, must not be chewed by the shorter rules
  sed -e "s|/opt/kb-convert-venv|$CVENV|g" \
      -e "s|/opt/kb-venv|$VENV|g" -e "s|/opt/kb-platform|$PREFIX|g" \
      "$u" > "/etc/systemd/system/$(basename "$u")"
done
systemd-tmpfiles --create /etc/tmpfiles.d/kb.conf
systemctl daemon-reload
# Monitoring, not workloads — always on, and never bounced by a code deploy.
systemctl enable --now kb-heartbeat.timer 2>/dev/null || true
systemctl enable --now kb-maintenance.timer 2>/dev/null || true
systemctl enable --now kb-gitgc.timer 2>/dev/null || true

if [ "$RESTART" -eq 1 ]; then
  echo "== restart =="
  UNITS="kb-syncd kb-hub kb-indexer kb-embedd"
  # kb-convert only exists where its venv was provisioned (scripts/install.sh)
  [ -x "$CVENV/bin/python" ] && UNITS="$UNITS kb-convert"
  # shellcheck disable=SC2086  # UNITS is a deliberate word list
  systemctl restart $UNITS
  sleep 2
  for s in $UNITS; do
    printf '  %-12s %s\n' "$s" "$(systemctl is-active "$s")"
  done
fi

# kb-embedd is new on existing boxes: enable it once (it sends nothing until
# keys exist). --no-restart still starts it if it is not running yet.
systemctl enable kb-embedd >/dev/null 2>&1 || true
systemctl is-active --quiet kb-embedd || systemctl start kb-embedd || true

# Semantic search is optional, like dictation: say so when it is not set up.
if [ "${KB_EMBED_PROVIDER:-none}" = "none" ]; then
  echo "  note: semantic search is off (KB_EMBED_PROVIDER=none) — see docs/semantic-search.md"
elif [ ! -s /etc/kb/embed.key ] && [ "${KB_EMBED_PROVIDER}" != "fake" ]; then
  echo "  WARNING: KB_EMBED_PROVIDER=${KB_EMBED_PROVIDER} but /etc/kb/embed.key is missing —"
  echo "           kb-embedd reports 'unconfigured'. sudo bash scripts/install-search-keys.sh --help"
fi

echo "== deploy complete =="
