#!/usr/bin/env bash
# Put the checked-out code live: code to the prefix, CLI wrappers, platform
# skills, database schema, systemd units and timers, then (re)start. The ONE
# copy of these steps — scripts/install.sh provisions a fresh machine and then
# runs this as its last step, so an install and a redeploy cannot drift apart.
#
# Reads the paths chosen at install time from /etc/kb/kb.env, so it follows a
# non-default --prefix automatically. Run as root:
#
#   sudo bash scripts/deploy.sh [--no-restart | --no-start]
#
#   --no-restart  leave running services alone (anything not running is started)
#   --no-start    install units and timers but enable and start nothing
#
# WARNING: restarting kb-hub kills every open web-terminal session. The units use
# systemd's default KillMode=control-group, and the per-user backends (plus their
# login shells) are spawned by the hub and therefore live in its cgroup. Check for
# live work first — `systemctl status kb-hub | sed -n '/CGroup/,$p'` — and pass
# --no-restart if someone is mid-session. kb-syncd, kb-indexer, kb-embedd and
# kb-convert contain only themselves, so those restarts are safe; a kb-syncd restart can
# however lose CRDT edits that have not yet been flushed to disk.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESTART=1 START=1
for arg in "$@"; do
  case "$arg" in
    --no-restart) RESTART=0 ;;
    --no-start)   START=0 RESTART=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

# Defaults match install.sh; /etc/kb/kb.env overrides them if it exists.
PREFIX=/opt/kb-platform
VENV=/opt/kb-venv
if [ -f /etc/kb/kb.env ]; then
  # shellcheck disable=SC1091
  . /etc/kb/kb.env
  PREFIX="${KB_PLATFORM_ROOT:-$PREFIX}"
  VENV="$(dirname "$(dirname "${KB_VENV_PY:-$VENV/bin/python}")")"
else
  echo "WARNING: /etc/kb/kb.env not found — is the platform installed? Using defaults."
fi

# --- version ---------------------------------------------------------------
# One number, written where every unit and the UI can read it. The tag is for
# people; the VERSION file is what a tarball without .git still has. A build
# off a tag reads exactly "1.0.0"; anything else carries its distance from the
# last tag, so a support conversation can tell a release from a working copy.
VERSION="$(cat "$SRC/VERSION" 2>/dev/null || echo 0.0.0)"
if git -C "$SRC" rev-parse --git-dir >/dev/null 2>&1; then
  DESC="$(git -C "$SRC" describe --tags --always --dirty 2>/dev/null || true)"
  [ -n "$DESC" ] && VERSION="${DESC#v}"
fi
echo "== version $VERSION =="

# Set one key in /etc/kb/kb.env without disturbing the others. install.sh
# writes the file wholesale; everything after it edits in place.
kbenv_set() {
  [ -f /etc/kb/kb.env ] || return 0
  sed -i "/^$1=/d" /etc/kb/kb.env
  printf '%s=%s\n' "$1" "$2" >> /etc/kb/kb.env
}
kbenv_set KB_VERSION "$VERSION"

echo "== code -> $PREFIX =="
mkdir -p "$PREFIX/frontend"
rsync -a --delete "$SRC/kb_platform" "$PREFIX/"
rsync -a --delete "$SRC/scripts"     "$PREFIX/"
if [ -d "$SRC/frontend/static" ] && [ -n "$(ls -A "$SRC/frontend/static" 2>/dev/null)" ]; then
  rsync -a --delete "$SRC/frontend/static" "$PREFIX/frontend/"
else
  echo "  (no frontend/static — run 'cd frontend && npm install && node build.mjs' first)"
fi
cp "$SRC/requirements.txt" "$PREFIX/" 2>/dev/null || true

echo "== permissions (world-readable code; NOT the session key) =="
# World-readable + executable: per-user backends run this code as their own uid.
CVENV="${VENV%/*}/kb-convert-venv"
for d in "$PREFIX" "$VENV" "$CVENV"; do
  [ -d "$d" ] || continue
  chown -R root:root "$d"
  chmod -R a+rX "$d"
done
# Runtime config is root's alone: the units read it through systemd, and it
# holds the alert topic (whoever knows it can read and forge alerts). An
# earlier install.sh left it 0644; every deploy puts that right.
if [ -f /etc/kb/kb.env ]; then
  chown root:root /etc/kb/kb.env
  chmod 0640 /etc/kb/kb.env
fi

# The kb-history wrapper is generated by install.sh, which nobody re-runs after
# the first install — so a fix to it never reached an existing box. That is not
# hypothetical: this wrapper sat here for weeks without the PYTHONPATH every
# systemd unit sets, and `kb-history` answered ModuleNotFoundError every time
# anyone tried the documented way to read version history. Regenerating it on
# every deploy is idempotent and costs nothing.
echo "== kb-history, kb-search and kb-telemetry CLIs =="
cat > /usr/local/bin/kb-history <<WRAP
#!/bin/sh
# Ollsoft Company OS version-history CLI. Regenerated by scripts/deploy.sh.
PYTHONPATH="$PREFIX" exec "$VENV/bin/python" -m kb_platform.vc_cli "\$@"
WRAP
chmod 0755 /usr/local/bin/kb-history
# kb-search: hybrid search as the caller (docs/semantic-search.md).
cat > /usr/local/bin/kb-search <<WRAP
#!/bin/sh
# Ollsoft Company OS search CLI. Regenerated by scripts/deploy.sh.
PYTHONPATH="$PREFIX" exec "$VENV/bin/python" -m kb_platform.search_cli "\$@"
WRAP
chmod 0755 /usr/local/bin/kb-search
# kb-telemetry: the honesty command. `kb-telemetry show` must work on any box
# without anyone hunting for a path, or "see exactly what is sent" is a slogan.
cat > /usr/local/bin/kb-telemetry <<WRAP
#!/bin/sh
# Ollsoft Company OS telemetry CLI. Regenerated by scripts/deploy.sh.
set -a; [ -f /etc/kb/kb.env ] && . /etc/kb/kb.env; set +a
exec "$PREFIX/scripts/kb-telemetry" "\$@"
WRAP
chmod 0755 /usr/local/bin/kb-telemetry

# The platform's skills (company-skills/) are platform code: install them on
# every deploy, like the CLI wrappers, or a fix never reaches an existing box.
# Only the platform's own — a skill the company wrote itself is left alone.
REPO_DIR="${KB_REPO:-/srv/kb}"
if [ -d "$REPO_DIR/.claude/skills" ]; then
  echo "== skills -> $REPO_DIR/.claude/skills =="
  for d in "$SRC"/company-skills/*/; do
    name="$(basename "$d")"
    install -d -m 0755 -o root -g kb-users "$REPO_DIR/.claude/skills/$name"
    install -m 0644 -o root -g kb-users "$d/SKILL.md" "$REPO_DIR/.claude/skills/$name/SKILL.md"
  done
fi

# schema.sql is idempotent (CREATE ... IF NOT EXISTS, CREATE OR REPLACE), so a
# deploy brings an existing database up to the code it ships — new tables such
# as kb.chunks and kb.embeddings included. One transaction: all or nothing.
# It re-creates the RLS policies on kb.blocks, which needs a moment's exclusive
# lock: lock_timeout keeps searches from queueing behind it while the indexer
# is mid-transaction, and the retry takes the next gap.
echo "== database schema =="
DB="${KB_PG_DB:-kb}"
runuser -u postgres -- psql -d "$DB" -qc "CREATE EXTENSION IF NOT EXISTS vector;" >/dev/null
runuser -u postgres -- psql -d "$DB" -qc "ALTER EXTENSION vector UPDATE;" >/dev/null 2>&1 || true
applied=0
for try in 1 2 3 4 5; do
  if PGOPTIONS="-c lock_timeout=3s" runuser -u kbindexer -- \
       psql -d "$DB" -q -1 -v ON_ERROR_STOP=1 < "$SRC/scripts/schema.sql" >/dev/null 2>"/tmp/kb-schema.$$"; then
    applied=1; break
  fi
  grep -q "lock timeout" "/tmp/kb-schema.$$" || break
  sleep "$try"
done
if [ "$applied" -eq 1 ]; then
  echo "  schema up to date"; rm -f "/tmp/kb-schema.$$"
else
  echo "!! schema.sql did not apply (nothing was changed):" >&2
  cat "/tmp/kb-schema.$$" >&2; rm -f "/tmp/kb-schema.$$"; exit 1
fi

echo "== systemd units =="
cp "$SRC/systemd/kb.conf" /etc/tmpfiles.d/kb.conf
cp "$SRC/systemd/kb-logrotate.conf" /etc/logrotate.d/kb
install -d -m 750 -o root -g root /var/log/kb
for u in "$SRC"/systemd/kb-*.service "$SRC"/systemd/kb-*.timer; do
  [ -e "$u" ] || continue
  # Tokenise all defaults BEFORE expanding any, or a --prefix that contains
  # another default gets substituted twice (e.g. /opt/kb-platform/kb-venv).
  # The convert venv goes first: longest path, must not be chewed by the others.
  sed -e "s|/opt/kb-convert-venv|@@CVENV@@|g" \
      -e "s|/opt/kb-venv|@@VENV@@|g"   -e "s|/opt/kb-platform|@@PREFIX@@|g" \
      -e "s|@@CVENV@@|$CVENV|g" \
      -e "s|@@VENV@@|$VENV|g"          -e "s|@@PREFIX@@|$PREFIX|g" \
      "$u" > "/etc/systemd/system/$(basename "$u")"
done
systemd-tmpfiles --create /etc/tmpfiles.d/kb.conf
systemctl daemon-reload

# kb-embedd always runs: without keys it only reports `unconfigured` and sends nothing.
# kb-convert only exists where its venv was provisioned (scripts/install.sh).
UNITS="kb-syncd kb-hub kb-indexer kb-embedd"
[ -x "$CVENV/bin/python" ] && UNITS="$UNITS kb-convert"
if [ "$START" -eq 0 ]; then
  echo "  units installed; nothing enabled or started (--no-start)"
else
  # Enabled on every run, so a unit or timer added by a later release reaches
  # existing boxes and a fresh install gets exactly the same set.
  # shellcheck disable=SC2086  # UNITS is a deliberate word list
  systemctl enable $UNITS >/dev/null 2>&1
  # Monitoring, not workloads — always on, and never bounced by a code deploy.
  systemctl enable --now kb-heartbeat.timer kb-maintenance.timer kb-gitgc.timer \
    kb-telemetry.timer kb-update.timer >/dev/null 2>&1 || true
  if [ "$RESTART" -eq 1 ]; then
    echo "== restart =="
    # restart, not just start: running units would otherwise keep executing
    # the previous code and environment.
    # shellcheck disable=SC2086
    systemctl restart $UNITS
    sleep 3
  else
    for s in $UNITS; do systemctl is-active --quiet "$s" || systemctl start "$s" || true; done
  fi
  FAILED=0
  for s in $UNITS; do
    st="$(systemctl is-active "$s")"
    printf '  %-12s %s\n' "$s" "$st"
    [ "$st" = "active" ] || FAILED=1
  done
  if [ "$FAILED" -ne 0 ]; then
    echo "ERROR: a service is not running. Diagnose with:" >&2
    echo "  journalctl -u kb-hub -u kb-syncd -u kb-indexer -u kb-embedd -u kb-convert -n 50 --no-pager" >&2
    exit 1
  fi
fi

# Semantic search is optional, like dictation: say so when it is not set up.
if [ "${KB_EMBED_PROVIDER:-none}" = "none" ]; then
  echo "  note: semantic search is off (KB_EMBED_PROVIDER=none) — see docs/semantic-search.md"
elif [ ! -s /etc/kb/embed.key ] && [ "${KB_EMBED_PROVIDER}" != "fake" ]; then
  echo "  WARNING: KB_EMBED_PROVIDER=${KB_EMBED_PROVIDER} but /etc/kb/embed.key is missing —"
  echo "           kb-embedd reports 'unconfigured'. sudo bash scripts/install-search-keys.sh --help"
fi

echo "== deploy complete =="
